services:
    mrapps.email:
        class: Mrapps\EmailBundle\Handler\EmailHandler
        arguments:  [@service_container]

    mrapps.email.twig.extension:
            class: Mrapps\EmailBundle\Twig\MrappsEmailTwigExtension
            arguments: [@service_container]
            tags:
                - { name: twig.extension }